	.align 2
voicegroup200::
	voice_keysplit_all voicegroup001
	voice_keysplit voicegroup005, KeySplitTable1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 216, 90, 242
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_special_scream_drive, 255, 0, 255, 195
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
	voice_directsound 60, 0, DirectSoundWaveData_trinity_big_boned, 255, 165, 154, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 235, 128, 115
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 252, 0, 115
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 204, 193, 239
	voice_keysplit voicegroup006, KeySplitTable2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 255, 0
	voice_keysplit voicegroup006, KeySplitTable2
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup007, KeySplitTable3
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup008, KeySplitTable4
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup009, KeySplitTable5
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 255, 127
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 72, 62, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_oboe, 43, 188, 103, 165
	voice_directsound 60, 0, DirectSoundWaveData_unused_sd90_oboe, 43, 165, 103, 165
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_1, 0, 7, 15, 1
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 191, 97, 165
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 2
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_7, 0, 7, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, 0, 7, 15, 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_7, 0, 7, 15, 2
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_60, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_72, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_84, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_60, 255, 0, 224, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_72, 255, 0, 218, 165
	voice_keysplit voicegroup008, KeySplitTable4
	voice_directsound 60, 0, DirectSoundWaveData_unknown_10, 255, 255, 255, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_1, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_low, 255, 0, 206, 242
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_1, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_3, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_4, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_5, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_6, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_7, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_8, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_unknown_9, 255, 249, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_10, 255, 255, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_11, 255, 255, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_unknown_12, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_13, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_14, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_15, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_16, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_17, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_unknown_18, 255, 0, 206, 204
